site_name: Underpass
site_description: Underpass updates a local copy of the OSM database in near real-time.
site_url: "https://github.com/emi420/underpass"

repo_name: "emi420/underpass"
repo_url: "https://github.com/emi420/underpass"
edit_uri: "edit/main/docs/"

theme:
  name: material
  palette:
    primary: custom

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Get Started:
      - Install: get-started/Install.md
      - Setup: get-started/Setup.md
      - Next steps: get-started/NextSteps.md
  - Replication:
      - Run: Replication/Run.md
      - Advanced: Replication/Advanced.md
  - Developers:
      - Coding: Dev/coding.md
      - Debugging: Dev/debugging.md
      - ChangeFile: Dev/changefile.md
      - Data flow: Dev/dataflow.md
      - Engine: Dev/engine.md
      - Replication: Dev/replication.md
      - Utility: Dev/utility.md
      - Chroots: Dev/chroots.md
      
