version: "3"

services:
  # PostGIS stock image
  postgis:
    image: postgis/postgis:11-2.5-alpine
    container_name: "underpass_postgis"
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=underpass
      - POSTGRES_USER=underpass
      - POSTGRES_PASSWORD=underpass
    volumes:
      - ../:/code/
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      internal:

  # Underpass build dependencies
  underpass-build-deps:
    # Pre-built for speed:
    image: quay.io/hotosm/underpass-build-deps:focal
    container_name: "underpass"
    # Build recipe:
    #build:
    #  context: .
    #  dockerfile: underpass-build-deps.dockerfile
    environment:
      - PGHOST=postgis
      - PGUSER=underpass
      - PGPASSWORD=underpass
      - UNDERPASS_SOURCE_TREE_ROOT=/code
    command: tail -f /dev/null
    volumes:
      - ../:/code/
    depends_on:
      - postgis
    networks:
      internal:

networks:
  internal:
