//
// Copyright (c) 2020, 2021, 2022, 2023, 2024 Humanitarian OpenStreetMap Team
//
// This file is part of Underpass.
//
//     Underpass is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "unconfig.h"
#endif

#include <algorithm>
#include <fstream>
#include <iostream>
#include <iterator>
#include <mutex>
#include <range/v3/all.hpp>
#include <string>
#include <thread>
#include <unistd.h>
#include <vector>
#include <sstream>
#include <chrono>

#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/thread/pthread/shared_mutex.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/asio.hpp>
#include <boost/thread/thread.hpp>
#include <boost/asio/thread_pool.hpp>
#include <boost/asio/ssl/error.hpp>
#include <boost/asio/ssl/stream.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/http/parser.hpp>
#include <boost/beast/version.hpp>
#include <boost/date_time.hpp>
#include <boost/dll/import.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/filtering_stream.hpp>
#include <boost/circular_buffer.hpp>

using namespace boost::posix_time;
using namespace boost::gregorian;
#include <boost/iostreams/filter/gzip.hpp>
#include <boost/iostreams/filtering_streambuf.hpp>
namespace beast = boost::beast;   // from <boost/beast.hpp>
namespace net = boost::asio;      // from <boost/asio.hpp>
namespace ssl = boost::asio::ssl; // from <boost/asio/ssl.hpp>
namespace http = beast::http;     // from <boost/beast/http.hpp>
using tcp = net::ip::tcp;         // from <boost/asio/ip/tcp.hpp>

#include <boost/config.hpp>
#include <boost/dll/runtime_symbol_info.hpp>
#include <boost/dll/shared_library.hpp>
#include <boost/function.hpp>
#include <boost/timer/timer.hpp>

#include "osm/osmobjects.hh"
#include "replicator/threads.hh"
#include "utils/log.hh"
#include "osm/changeset.hh"
#include "osm/osmchange.hh"
#include "replicator/replication.hh"
#include "raw/queryraw.hh"
#include "raw/geobuilder.hh"
#include <jemalloc/jemalloc.h>
#include "data/pq.hh"
#include "underpassconfig.hh"


std::mutex stream_mutex;

using namespace logger;
using namespace queryraw;
using namespace geobuilder;
using namespace underpassconfig;

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

namespace replicatorthreads {

std::string
allTasksQueries(std::shared_ptr<std::vector<ReplicationTask>> tasks) {
    std::string queries;
    for (auto it = tasks->begin(); it != tasks->end(); ++it) {
        for (auto itt = it->query.begin(); itt != it->query.end(); ++itt) {
            queries.append(*itt);
        }
    }
    return queries;
}

// Get closest change from a list of tasks
std::shared_ptr<ReplicationTask>
getClosest(std::shared_ptr<std::vector<ReplicationTask>> tasks, ptime now) {
    ReplicationTask closest;
    if (tasks->size() > 0) {
        closest = tasks->at(0);
        for (auto it = tasks->begin(); it != tasks->end(); ++it) {
            if (it->timestamp != not_a_date_time) {
                boost::posix_time::time_duration delta = now - it->timestamp;
                boost::posix_time::time_duration delta_oldest = now - closest.timestamp;
                if (delta.hours() * 60 + delta.minutes() < delta_oldest.hours() * 60 + delta_oldest.minutes()) {
                    closest = *it;
                }
            }
        }
    }
    return std::make_shared<ReplicationTask>(closest);
}

// Starting with this URL, download the file, incrementing
void
startMonitorChangesets(std::shared_ptr<replication::RemoteURL> &remote,
               const multipolygon_t &poly,
               const UnderpassConfig config)
{
#ifdef TIMING_DEBUG
    boost::timer::auto_cpu_timer timer("startMonitorChangesets: took %w seconds\n");
#endif
    // This function is for changesets only!
    assert(remote->frequency == frequency_t::changeset);

    auto db = std::make_shared<Pq>();
    if (!db->connect(config.underpass_db_url)) {
        log_error("Could not connect to Underpass DB, aborting monitoring thread!");
        return;
    } else {
        log_debug("Connected to database: %1%", config.underpass_db_url);
    }

    int cores = config.concurrency;

    // Support multiple OSM planet servers
    std::vector<std::shared_ptr<replication::Planet>> planets;
    std::vector<std::string> servers;
    for (auto it = std::begin(config.planet_servers); it != std::end(config.planet_servers); ++it) {
        servers.push_back(it->domain);
    }

    // Rotate OSM Planet servers
    int i = 0;
    while (i <= cores/4) {
        std::rotate(servers.begin(), servers.begin()+1, servers.end());
        auto replicationPlanet = std::make_shared<replication::Planet>(*remote);
        planets.push_back(replicationPlanet);
        i++;
    }

    // Process Changesets replication files
    ReplicationTask closest;
    auto delay = std::chrono::seconds{0};
    auto last_task = std::make_shared<ReplicationTask>();
    bool caughtUpWithNow = false;
    bool monitoring = true;

    while (monitoring) {
        auto tasks = std::make_shared<std::vector<ReplicationTask>>();
        i = cores*2;
        boost::asio::thread_pool pool(i);
        while (--i) {
            std::this_thread::sleep_for(delay);
            if (last_task->status == reqfile_t::success ||
                (last_task->status == reqfile_t::remoteNotFound && !caughtUpWithNow)) {
                remote->increment();
                if (!config.silent) {
                    remote->dump();
                }
            }
            auto new_remote = std::make_shared<replication::RemoteURL>(remote->getURL());
            new_remote->destdir_base = remote->destdir_base;
            auto task = boost::bind(threadChangeSet,
                new_remote,
                std::ref(planets.front()),
                std::ref(poly),
                std::ref(tasks)
            );

            boost::asio::post(pool, task);
            std::rotate(planets.begin(), planets.begin()+1, planets.end());
            remote->updateDomain(planets.front()->domain);
        }
        pool.join();
        db->query(allTasksQueries(tasks));

        ptime now  = boost::posix_time::second_clock::universal_time();
        last_task = getClosest(tasks, now);
        if (last_task->timestamp != not_a_date_time) {
            closest.url = std::string(last_task->url);
            closest.timestamp = ptime(last_task->timestamp);
            if (last_task->timestamp >= config.end_time) {
                monitoring = false;
            }
        }
        // Check if caught up with now
        if (!caughtUpWithNow) {
            boost::posix_time::time_duration delta_closest = now - closest.timestamp;
            if (delta_closest.hours() * 60 + delta_closest.minutes() <= 2) {
                caughtUpWithNow = true;
                log_debug("Caught up with: %1%", closest.url);
                remote->updatePath(
                    std::stoi(closest.url.substr(0, 3)),
                    std::stoi(closest.url.substr(4, 3)),
                    std::stoi(closest.url.substr(8, 3))
                );
                if (!config.silent) {
                    remote->dump();
                }
                cores = 1;
                delay = std::chrono::seconds{45};
            }
        }
    }
}

// Starting with this URL, download the file, incrementing
void
startMonitorChanges(std::shared_ptr<replication::RemoteURL> &remote,
            const multipolygon_t &poly,
            const UnderpassConfig &config)
{
#ifdef TIMING_DEBUG
    boost::timer::auto_cpu_timer timer("startMonitorChanges: took %w seconds\n");
#endif
    if (remote->frequency == frequency_t::changeset) {
        log_error("Could not start monitoring thread for OSM changes: URL %1% does not appear to be a valid URL for changes!", remote->filespec);
        return;
    }

#ifdef MEMORY_DEBUG
    size_t sz, active1, active2;
#endif    // JEMALLOC memory debugging
    auto db = std::make_shared<Pq>();
    if (!db->connect(config.underpass_db_url)) {
        log_error("Could not connect to Underpass DB, aborting monitoring thread!");
        return;
    } else {
        log_debug("Connected to database: %1%", config.underpass_db_url);
    }
    auto queryraw = std::make_shared<QueryRaw>(db);

    int cores = config.concurrency;

    // Support multiple OSM planet servers
    std::vector<std::shared_ptr<replication::Planet>> planets;
    std::vector<std::string> servers;
    for (auto it = std::begin(config.planet_servers); it != std::end(config.planet_servers); ++it) {
        servers.push_back(it->domain);
    }

    // Rotate OSM Planet servers
    int i = 0;
    while (i <= cores/4) {
        std::rotate(servers.begin(), servers.begin()+1, servers.end());
        auto replicationPlanet = std::make_shared<replication::Planet>(*remote);
        planets.push_back(replicationPlanet);
        i++;
    }

    // Process OSM changes
    auto delay = std::chrono::seconds{0};
    ReplicationTask closest;
    auto last_task = std::make_shared<ReplicationTask>();
    last_task->status = reqfile_t::success;
    bool caughtUpWithNow = false;
    bool monitoring = true;
    auto underpassConfig = std::make_shared<UnderpassConfig>(config);
    int concurrentTasks = cores*2;

    while (monitoring) {
        auto tasks = std::make_shared<std::vector<ReplicationTask>>(concurrentTasks);
        boost::asio::thread_pool pool(concurrentTasks);
        i = concurrentTasks;
        do {
            std::this_thread::sleep_for(delay);
            if (last_task->status == reqfile_t::success ||
                (last_task->status == reqfile_t::remoteNotFound && !caughtUpWithNow)) {
                remote->increment();
                if (!config.silent) {
                    remote->dump();
                }
            }
            auto new_remote = std::make_shared<replication::RemoteURL>(remote->getURL());
            new_remote->destdir_base = remote->destdir_base;
            OsmChangeTask osmChangeTask {
                new_remote,
                std::ref(planets.front()),
                std::ref(poly),
                std::ref(tasks),
                std::ref(queryraw),
                underpassConfig,
                concurrentTasks - i
            };

            auto task = boost::bind(threadOsmChange, osmChangeTask);
            std::rotate(planets.begin(), planets.begin()+1, planets.end());

            boost::asio::post(pool, task);
        } while (--i);
        pool.join();
        db->query(allTasksQueries(tasks));

        ptime now  = boost::posix_time::second_clock::universal_time();
        last_task = getClosest(tasks, now);
        if (last_task->timestamp != not_a_date_time) {
            closest.url = std::string(last_task->url);
            closest.timestamp = ptime(last_task->timestamp);
            if (last_task->timestamp >= config.end_time) {
                monitoring = false;
            }
        }
        // Check if caught up with now
        if (!caughtUpWithNow) {
            boost::posix_time::time_duration delta_closest = now - closest.timestamp;
            if (delta_closest.hours() * 60 + delta_closest.minutes() <= 2) {
                caughtUpWithNow = true;
                log_debug("Caught up with: %1%", closest.url);
                remote->updatePath(
                    std::stoi(closest.url.substr(0, 3)),
                    std::stoi(closest.url.substr(4, 3)),
                    std::stoi(closest.url.substr(8, 3))
                );
                if (!config.silent) {
                    remote->dump();
                }
                concurrentTasks = 1;
                delay = std::chrono::seconds{45};
            }
        }
    }
}

// This parses the changeset file into changesets
void
threadChangeSet(std::shared_ptr<replication::RemoteURL> &remote,
        std::shared_ptr<replication::Planet> &planet,
        const multipolygon_t &poly,
        std::shared_ptr<std::vector<ReplicationTask>> tasks)
{
#ifdef TIMING_DEBUG
    boost::timer::auto_cpu_timer timer("threadChangeSet: took %w seconds\n");
#endif
    ReplicationTask task;
    task.url = remote->subpath;
    auto file = planet->downloadFile(*remote.get());
    task.status = file.status;

    if (file.status == reqfile_t::success) {
        auto changeset = std::make_unique<changesets::ChangeSetFile>();
        log_debug("Processing ChangeSet: %1%", remote->filespec);
        auto xml = planet->processData(remote->filespec, *file.data);
        std::istream& input(xml);
        changeset->readXML(input);
        if (changeset->last_closed_at != not_a_date_time) {
            task.timestamp = changeset->last_closed_at;
        } else if (changeset->changes.size() && changeset->changes.back()->created_at != not_a_date_time) {
            task.timestamp = changeset->changes.back()->created_at;
        }
        log_debug("ChangeSet last_closed_at: %1%", task.timestamp);
        changeset->areaFilter(poly);
    }
    const std::lock_guard<std::mutex> lock(tasks_changeset_mutex);
    tasks->push_back(task);
}

// This thread get started for every osmChange file
void
threadOsmChange(OsmChangeTask osmChangeTask)
{
#ifdef TIMING_DEBUG
    boost::timer::auto_cpu_timer timer("threadOsmChange: took %w seconds\n");
#endif
    auto remote = osmChangeTask.remote;
    auto planet = osmChangeTask.planet;
    auto poly = osmChangeTask.poly;
    auto tasks = osmChangeTask.tasks;
    auto queryraw = osmChangeTask.queryraw;
    auto config = osmChangeTask.config;
    auto taskIndex = osmChangeTask.taskIndex;

    auto osmchanges = std::make_shared<osmchange::OsmChangeFile>();
    log_debug("Processing OsmChange: %1%", remote->filespec);
    ReplicationTask task;
    task.url = remote->subpath;
    auto file = planet->downloadFile(*remote.get());
    task.status = file.status;

    // Read OsmChange
    if (file.status == replication::success) {
        try {
            std::istringstream changes_xml;
            // Scope to deallocate buffers
            {
                boost::iostreams::filtering_streambuf<boost::iostreams::input> inbuf;
                inbuf.push(boost::iostreams::gzip_decompressor());
                boost::iostreams::array_source arrs{reinterpret_cast<char const *>(file.data->data()), file.data->size()};
                inbuf.push(arrs);
                std::istream instream(&inbuf);
                changes_xml.str(std::string{std::istreambuf_iterator<char>(instream), {}});
            }

            try {
                osmchanges->readXML(changes_xml);
                if (osmchanges->changes.size() > 0) {
                    task.timestamp = osmchanges->changes.back()->final_entry;
                    // log_debug("OsmChange final_entry: %1%", task.timestamp);
                }
            } catch (std::exception &e) {
                log_error("Couldn't parse: %1%", remote->filespec);
                std::filesystem::remove(remote->filespec);
                std::cerr << e.what() << std::endl;
            }

        } catch (std::exception &e) {
            log_error("%1% is corrupted!", remote->filespec);
            std::filesystem::remove(remote->filespec);
            std::cerr << e.what() << std::endl;
        }
    }

    // Build features geometries
    GeoBuilder geobuilder(poly, queryraw);
    geobuilder.buildGeometries(osmchanges);
    osmchanges->areaFilter(poly);

    // Raw data
    for (auto it = std::begin(osmchanges->changes); it != std::end(osmchanges->changes); ++it) {
        osmchange::OsmChange *change = it->get();

        // Nodes
        for (auto nit = std::begin(change->nodes); nit != std::end(change->nodes); ++nit) {
            osmobjects::OsmNode *node = nit->get();

            if (!node->priority) {
                continue;
            }

            //  Update nodes, ignore new ones outside priority area
            auto changes = queryraw->applyChange(*node);
            for (auto it = changes->begin(); it != changes->end(); ++it) {
                    task.query.push_back(*it);
            }
        }

        // Ways
        for (auto wit = std::begin(change->ways); wit != std::end(change->ways); ++wit) {
            osmobjects::OsmWay *way = wit->get();

            // Skip if not priority or disabled
            if (way->action != osmobjects::remove && !way->priority) {
                continue;
            }

            //  Update ways, ignore new ones outside priority area
            auto changes = queryraw->applyChange(*way);
            for (auto it = changes->begin(); it != changes->end(); ++it) {
                task.query.push_back(*it);
            }
        }

        // Relations
        for (auto rit = std::begin(change->relations); rit != std::end(change->relations); ++rit) {
            osmobjects::OsmRelation *relation = rit->get();

            if (relation->action != osmobjects::remove && !relation->priority) {
                continue;
            }
            //  Update relations, ignore new ones outside priority area
            auto changes = queryraw->applyChange(*relation);
            for (auto it = changes->begin(); it != changes->end(); ++it) {
                task.query.push_back(*it);
            }
        }
    }

    const std::lock_guard<std::mutex> lock(tasks_change_mutex);
    (*tasks)[taskIndex] = task;

}

} // namespace replicatorthreads

// local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
