name: 🔧 Build CI Img

on:
  # Push includes PR merge
  push:
    branches:
      - master
    paths:
      - docker/**
      - .github/workflows/**
  # Allow manual trigger
  workflow_dispatch:

jobs:
  underpass-ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.4.1
    with:
      dockerfile: docker/underpass.dockerfile
      scan_dockerfile: false
      scan_image: false
      build_target: ci
      image_tags: |
        "ghcr.io/${{ github.repository }}:ci"

  invalidate-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete CI Img Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete image-cache-${{ runner.os }} \
            -R ${{ github.repository }} \
            -B ${{ github.ref_name }} \
            --confirm || true
