name: 🧪 Build and test

on:
  push:
    branches:
      - master
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Relies on the master branch built docker image for build-deps
      - name: Start Docker Compose & build
        run: cd docker && docker-compose up -d underpass
      # Build and run tests
      - name: Build and run tests 
        run: |
          docker-compose -f docker-compose.yml exec -T underpass sh -c "cd /code/build && make check -j `nproc`"
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Test failed with exit code $exit_code"
            exit $exit_code
          fi